### ISSUE TITLE
Where to find the documentation for the lower level serial protocol?

### ISSUE THREAD

**Issue by helarsen** [FLIR/rawBoson#13]
I have looked through the https://www.flir.com/globalassets/imported-assets/document/boson_sdk_documentation_9hz-v11412-and-later.pdf
but it does not contain information about the lower level serial protocol. Where could I get this documentation?

**Comment by ghost** [comment]
RawBoson is the lowest implementation of the protocol. This is what this SW does. However, in order to use it, you need to know what are the Boson commands that are available. The document tells you that. 
Once you know the command, rawBoson helps you to open the serial port, format the command into the right package, and send that over serial port.

As for example:
bosonGetCameraSN()   returns Serial Number ->  ( FunctionID 0x00050002  with no parameters ) 

in order to send this to the camera you use:
./rawBoson c50002    ( please note that you might need to add your serial port if different from default )

if you activate verbose then you will see output package and replay from camera

**Comment by ghost** [comment]
Please note, that the SDK facilitates and avoids you having to read the document. The SDK implements the functions that you can call from your SW directly, without the need of this rawBoson.  This SW is intended for those cases where SDK is not suitable for whatever reason.

**Comment by helarsen** [comment]
Thanks for taking time to reply to my question. I should explain a bit more.

I currently use the [https://github.com/LJMUAstroecology/flirpy](url) and as such it takes care of the low level lifting like you describe. I do however have a problem with the serial commands when the program starts up:

Somehow the first queries do not get a proper reply (terminated by 0xAE) - in fact the first couples are timing out, then there is a subsequent sequence of replies where all "the ketchup" suddenly comes - looks like the data was held back and now comes in a big chunk (although i have not analyzed the detail but  the reply looks a lot like a replica of old stale replies. After that is flushed the system runs normally.

This is when the camera is attached via an **[usb - extender VirtualHere](https://www.virtualhere.com/home).** When connected as usual with USB direct cables, this is not happening, and it works correctly.

So I was, and still is, trying to figure out what is going on when I realized I missed the glory low level details. That said I am not sure it would be of much help. But if I have the documentation it would maybe hold some additional information.

By the way, setup is 
> 2x Boson <-usb--> RaspberryPi4(VirtualHere server) <-Ethernet-> win10(VirtualHere client)

Normally the VirtualHere software works very well but it is suspicious that it fails only when VirtualHere is active. But debugging is difficult.

I am on the edge of giving up and start the program with a series of commands (like get serial) launched with small time-out and where errors are dumped to clean out stale data. Not nice but best for the moment

thanks for reading to here and any clews are welcome of course.

**Comment by ghost** [comment]
Well, i am not sure about all the steps that you have in the middle. What i can confirm is what you said. If you just connect to Boson-USB it works ( at least with rawBoson). There is no buffer, no need to flush, etc... rawBoson code shows you the details of what needs to happen ( checksums, start, stop, etc) but you should be able to get exactly the same from the flirpy. 
Not sure how to debug your case, but i can tell you that using Linux  ( RPI - ethernet - Linux PC ) I have made it work with serial ports. So, i know it is feasible at least with linux environments.  In my case i used SOCAT.

**Comment by helarsen** [comment]
Good to know. I had a quick look at [SOCAT](https://www.redhat.com/sysadmin/getting-started-socat). It looks great, but unfortunately I am locked to use a windows client. 

What kind of video speed do you get with SOCAT? Is it much different than a direct USB link?

I know there are other virtual usb alternatives out there but have not had time to investigate other.

**Comment by ghost** [comment]
i don't remember now and not sure about the speed... i believe we were still using USB2 at that time.... but don't know.
