### ISSUE TITLE
Boson module bricked (Averager).

### ISSUE THREAD

**Issue by logotype** [FLIR/rawBoson#14]
Hi

I used Boson GUI 1.5.0 to try out some settings. All good until I tried enabling the "Averager" functionality (I clicked Save and Reboot). When the Boson restarted, it completely freezes after the Splash screen is displayed. I think this is due to that the OTS firmware expects a 60Hz datastream, and Averager changes the framerate to half at 30Hz.
I can't use Boson GUI since the device completely freezes, so there isn't enough time to manually click in the GUI to restore to factory defaults/change undo the settings.

That's why i'm trying to use rawBoson to programmatically change settings, but it still doesn't work.

Here's one set of commands i've tried, disable averager & freeze, then save:
```bash
rawBoson -p/dev/ttyACM0 -b921600 c0000B x0 x0 x0 x0 v b # Disable Averager
rawBoson -p/dev/ttyACM0 -b921600 cE0001 x0 x0 x0 x0 v b # Disable Freeze
rawBoson -p/dev/ttyACM0 -b921600 c50018 v b # Write settings
```

Another set of commands, try to restore to factory defaults, write and then reboot:
```bash
rawBoson -p/dev/ttyACM0 -b921600 c5001B v b # Restore to factory defaults
rawBoson -p/dev/ttyACM0 -b921600 c50018 v b # Write settings
rawBoson -p/dev/ttyACM0 -b921600 c50010 v a # Reboot Boson
```

I do get response from the device briefly, for a split second after the splash screen is displayed. So it looks like the Boson module receives the commands, but fails to properly apply the settings before it freezes.

Wondering if you have any ideas on how to resolve the issue? Wouldn't want to throw rather expensive equipment in the bin.

Product: FLIR Breach (PTQ136).
OTS SW VERSION: 2567
BOSON SW VERSION: 2.0.14857

**Comment by ghost** [comment]
unfortunately this is out of my knowledge. I am wondering if through the normal SDK is there a way to recover that camera, but don't know. At this point i recommend you asking your service support point. It is weird that using Boson GUI you got into that state... i hope my colleagues at FLIR can provide you a solution, sending the core to the bin sounds terrible.
