### ISSUE TITLE
CRC error reported consistently -- error in rawBoson or camera firmware?

### ISSUE THREAD

**Issue by drjasonharrison-vp-eio** [FLIR/rawBoson#3]
If you run rawBoson requesting a changing value from the camera, such as frame count:
```
while true ; do ../rawBoson/rawBoson c0020002; done
```
you will encounter frame counts where CRC errors are reported in interesting patterns:
```
0x00 0x03 0x25 0x96 
0x00 0x03 0x25 0x97 
0x00 0x03 0x25 0x97 
0x00 0x03 0x25 0x98 
0x00 0x03 0x25 0x99 
>>> Error : Boson Bad CRC Received 
>>> Error : Boson Bad CRC Received 
0x00 0x03 0x25 0x9B 
0x00 0x03 0x25 0x9C 
0x00 0x03 0x25 0x9D 
>>> Error : Boson Bad CRC Received 
>>> Error : Boson Bad CRC Received 
0x00 0x03 0x25 0x9F 
0x00 0x03 0x25 0xA0 
0x00 0x03 0x25 0xA1 
0x00 0x03 0x25 0xA1 
```

Is this an error in rawBoson, or the camera firmware?
Adding the `v` flag to the rawBoson command produces more information.

**Comment by ghost** [comment]
Interesting. You are right. I am seeing that too. 
I think this is related to the other issue that we have. The code is doing bitstuffing but aparently is not working properly. 
So, most probably Boson is doing good, but rawBoson fails from time to time depending on the values received. 
this is a good catch and we will work on it now. 
Thanks

**Comment by drjasonharrison-vp-eio** [comment]
If you comment out line 335:

```
//		return -4;
```

then you can see that the amount of data identified as the response (excluding USB status, sequence number, CRC) varies between four bytes (expected) plus or minus a byte (unexpected).

```
0x00 0x01 0xCB 0x1B 
0x00 0x01 0xCB 0x1C 
0x00 0x01 0xCB 0x1D 0x9E 
0x00 0x01 0xCB 0x1D 0x9E 
0x00 0x01 0xCB 0x1E 0x9E 
0x00 0x01 0xCB 0x1F 0x9E 
0x00 0x01 0xCB 0x20 
0x00 0x01 0xCB 0x21 
```

```0x00 0x01 0xCB 0x3A 
0x00 0x01 0xCB 0x3B 
0x00 0x01 0xCB 
0x00 0x01 0xCB 
0x00 0x01 0xCB 0x3D 
0x00 0x01 0xCB 0x3E 
```

```
./rawBoson c00050022
0x00 0x00 0x00 0x02 0x00 0x00 0x00 0x00 0x00 0x00 0x33 0x51 
```
2.0.13137

**Comment by ghost** [comment]
I think i found the error. It is in the package sent to the Boson that has an incorrect bitstuffing so then the answer is bad and the CRC was failing. 

I have been running the while c20002 without seeing the error anymore. 
I had to change the BitStuffing function... weird values where there !

checkout code again and let me know if you still the issue. <Develop branch>

**Comment by ghost** [comment]
I have the change in DEVELOP branch, not in MASTER

**Comment by drjasonharrison-vp-eio** [comment]
line 402 should be changed to use 0x9E as the value to look for. Leaving it as 0x9A leaves lots of errors.
Not sure why adding 0xD is required by Boson.  Is this specific to Boson or USB?

**Comment by ghost** [comment]
YES, sorry my bad in the commit !!!! I had to do it manually (github web) since from here i don't have access from my computer

**Comment by drjasonharrison-vp-eio** [comment]
Thanks, it works much better. When I use it I'm not seeing any errors!

**Comment by ghost** [comment]
Great.

I have been told that Boson accepts two ESCAPE profiles but uses only one when transmitting to the PC.
Looking to the code again, the error was a typo in line 402:
BAD:   if ( boson_stuffed_package[i]==0x9A)   ( this is what MASTER had )
GOOD:    if ( boson_stuffed_package[i]==0x9E)  ( this is what should have been ) 

So, it was much simpler , just a typo, i am glad that we found this. I will revert some changes to use the recommended approach and we should be all good.

If you don't mind checking again DEVELOP will be great, if it works for you i will merge to MASTER later

Thanks for the help !

**Comment by ghost** [comment]
I have been running the SW since Friday and i din't get any CRC issues. 
I am closing this ticket. Thank you for finding the issue !

**Comment by drjasonharrison-vp-eio** [comment]
Thank you, everything looks good on my end too.
