### ISSUE TITLE
serial.c: setup_serial - should return 0 when successful

### ISSUE THREAD

**Issue by drjasonharrison-vp-eio** [FLIR/rawBoson#6]
Just noticed that setup_serial returns -1 if it does not encounter any errors. However it returns -1 if it does encounter errors.

https://github.com/FLIR/rawBoson/blob/de31e8e782e28fce2ee62cf3f1d3b2925ed928d1/serial.c#L322

at the same time, the code that calls setup_serial checks for 0 as an error, and any other value as successful:

https://github.com/FLIR/rawBoson/blob/de31e8e782e28fce2ee62cf3f1d3b2925ed928d1/serial.c#L18

I see that the other functions in serial.c return 0 on failure, and 1 on success. Perhaps this is how setup_serial was originally meant to work?

**Comment by andrespmt** [comment]
Oh my gosh ! that is terrible !... well, is one of the reasons unit test make sense.
Thank you for sharing, we will fix that. Have you done the modifications? why don't you sent a pull-request? 

Just for the records: This code has been reused and modified without paying attention to consistency between the main functions that were calling it... that is the reason...  however, we should have reviewed more carefully... but i am glad that you send the feedback
